listen_addr: ":8080"

routes:
  - prefix: /services
    upstream: https://api-alpha.example.net
  - prefix: /workout
    upstream: https://api-beta.example.net
  - prefix: /core
    upstream: https://api-gamma.example.net
  - prefix: /reporting
    upstream: https://api-delta.example.net
  - prefix: /cms
    upstream: https://api-epsilon.example.net
  - prefix: /services
    upstream: https://api-alpha.example.net
  - prefix: /link
    upstream: https://api-zeta.example.net
  - prefix: /iotcore
    upstream: https://api-eta.example.net
  - prefix: /echo
    upstream: http://localhost:9999
