name: release-publish-image

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-1
  AWS_ECR_ACCOUNT: 771964207937
  IMAGE_NAME: mini-rproxy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go (for potential build artifacts)
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Derive version from tag
        id: ver
        run: |
          RAW_TAG="${{ github.event.release.tag_name }}"
            # strip leading v if present (v1.2.3 -> 1.2.3)
          CLEAN_TAG="${RAW_TAG#v}"
          echo "raw_tag=$RAW_TAG" >> $GITHUB_OUTPUT
          echo "clean_tag=$CLEAN_TAG" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::771964207937:role/bff-shared-github-actions-role # <-- replace
          role-session-name: "sn-${{ github.event.repository.name }}@${{ github.run_number }}"
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr describe-repositories --repository-names "${{ env.IMAGE_NAME }}" >/dev/null 2>&1 || \
            aws ecr create-repository --repository-name "${{ env.IMAGE_NAME }}" >/dev/null
          aws ecr get-login-password --region ${{ env.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ env.AWS_ECR_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Make build
        run: |
          make build

      - name: Build & Push image
        run: |
          REGISTRY="${{ env.AWS_ECR_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"
          VERSION="${{ steps.ver.outputs.clean_tag }}"
          IMAGE="$REGISTRY/${{ env.IMAGE_NAME }}"
          docker build -t "$IMAGE:$VERSION" -t "$IMAGE:latest" .
          docker push "$IMAGE:$VERSION"
          docker push "$IMAGE:latest"

      - name: Output image tags
        run: |
          echo "Pushed:"
          echo "  ${{ env.AWS_ECR_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ steps.ver.outputs.clean_tag }}"
          echo "  ${{ env.AWS_ECR_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:latest"
